# Generated by Django 3.1.3 on 2020-11-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterasset",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactercontact",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactercontactlabel",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactercontract",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactercontractbid",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactercontractitem",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactercorporationhistory",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterdetails",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterdoctrineshipcheck",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterimplant",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterjumpclone",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterjumpcloneimplant",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterlocation",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterloyaltyentry",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactermail",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactermailinglist",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactermaillabel",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactermailrecipient",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="charactermailunreadcount",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characteronlinestatus",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterskill",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterskillpoints",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterskillqueueentry",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterupdatestatus",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterwalletbalance",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="characterwalletjournalentry",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="doctrine",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="doctrineship",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="doctrineshipskill",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"default_permissions": ()},
        ),
    ]
