# Generated by Django 3.1.1 on 2020-10-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="total_unread_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
