# Generated by Django 2.2.10 on 2020-09-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecipient',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='memberaudit.Mail'),
        ),
    ]
