# Generated by Django 3.1.1 on 2020-09-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0002_load_eveunit'),
        ('memberaudit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('owner', models.OneToOneField(help_text='character this mailling list belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner_characters_detail', serialize=False, to='memberaudit.owner')),
                ('birthday', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('security_status', models.FloatField(blank=True, default=None, null=True)),
                ('title', models.TextField(blank=True, default='')),
                ('alliance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner_alliances', to='eveuniverse.eveentity')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_corporations', to='eveuniverse.eveentity')),
                ('eve_ancestry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eveuniverse.eveancestry')),
                ('eve_bloodline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evebloodline')),
                ('faction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eveuniverse.evefaction')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.everace')),
            ],
        ),
    ]
