# Generated by Django 3.1.3 on 2020-11-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0002_auto_20201117_1922"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailEntity",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AL", "Alliance"),
                            ("CH", "Character"),
                            ("CO", "Corporation"),
                            ("ML", "Mailing List"),
                            ("UN", "Unknown"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="charactermailrecipient",
            name="eve_entity",
        ),
        migrations.RemoveField(
            model_name="charactermailrecipient",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="charactermailrecipient",
            name="mailing_list",
        ),
        migrations.RemoveField(
            model_name="charactermail",
            name="from_entity",
        ),
        migrations.RemoveField(
            model_name="charactermail",
            name="from_mailing_list",
        ),
        migrations.DeleteModel(
            name="CharacterMailingList",
        ),
        migrations.DeleteModel(
            name="CharacterMailRecipient",
        ),
        migrations.AddField(
            model_name="charactermail",
            name="recipients",
            field=models.ManyToManyField(
                related_name="recipient_mails", to="memberaudit.MailEntity"
            ),
        ),
        migrations.AddField(
            model_name="charactermail",
            name="sender",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_mails",
                to="memberaudit.mailentity",
            ),
        ),
    ]
