# Generated by Django 3.1.4 on 2020-12-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0002_add_share_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterupdatestatus",
            name="parent_task_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="ID of character_update task that started this update",
                max_length=36,
            ),
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="root_task_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="ID of update_all_characters task that started this update",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="finished_at",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="started_at",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
