# Generated by Django 3.1.1 on 2020-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "memberaudit",
            "0002_charactercontract_charactercontractbid_charactercontractitem",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("CD", "character details"),
                    ("CR", "contracts"),
                    ("CH", "corporation history"),
                    ("JC", "jump clones"),
                    ("MA", "mails"),
                    ("SK", "skills"),
                    ("WB", "wallet balance"),
                    ("WJ", "wallet journal"),
                ],
                max_length=2,
            ),
        ),
    ]
