# Generated by Django 3.1.1 on 2020-10-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_remove_fleetup_permission"),
        ("memberaudit", "0002_character_total_unread_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="character_ownership",
            field=models.OneToOneField(
                help_text="character registered to member audit",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberaudit_character",
                to="authentication.characterownership",
            ),
        ),
    ]
