# Generated by Django 3.1.1 on 2020-10-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0002_auto_20200930_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSyncStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("CD", "character details"),
                            ("CH", "corporation history"),
                            ("MA", "mails"),
                            ("SK", "skills"),
                            ("WB", "wallet balance"),
                            ("WJ", "wallet journal"),
                        ],
                        max_length=2,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_status_set",
                        to="memberaudit.character",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="charactersyncstatus",
            constraint=models.UniqueConstraint(
                fields=("character", "topic"),
                name="functional_pk_character_sync_status",
            ),
        ),
    ]
