# Generated by Django 3.1.1 on 2020-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0002_characterdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='character',
            new_name='character_ownership',
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
