# Generated by Django 3.1.1 on 2020-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0003_auto_20201001_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersyncstatus",
            name="sync_ok",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
