# Generated by Django 3.1.1 on 2020-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0003_auto_20201001_2324"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("unrestricted_access", "Can view all characters and data"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="Memberaudit",
        ),
    ]
