# Generated by Django 3.1.1 on 2020-10-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0003_auto_20201003_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
