# Generated by Django 3.1.1 on 2020-09-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0002_load_eveunit'),
        ('memberaudit', '0003_auto_20200926_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.PositiveIntegerField(db_index=True)),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, default=None, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.eveentity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberaudit.owner')),
            ],
        ),
    ]
