# Generated by Django 3.1.3 on 2020-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0004_auto_20201129_1953"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterupdatestatus",
            old_name="content_hash",
            new_name="content_hash_1",
        ),
        migrations.RemoveField(
            model_name="characterupdatestatus",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="content_hash_2",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="content_hash_3",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="finished_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="started_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
