# Generated by Django 3.1.1 on 2020-10-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0004_auto_20201002_1212"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "basic_access",
                        "Can access this app and register and view his characters",
                    ),
                    (
                        "corporation_access",
                        "Can view characters and data of his main's corporation",
                    ),
                    (
                        "alliance_access",
                        "Can view characters and data of his main's alliance",
                    ),
                    ("unrestricted_access", "Can view all characters and data"),
                ),
            },
        ),
    ]
