# Generated by Django 3.1.1 on 2020-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0004_auto_20201010_1301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactercontract",
            name="availability",
            field=models.CharField(
                choices=[
                    ("AL", "alliance"),
                    ("CO", "corporation"),
                    ("PR", "private"),
                    ("PU", "public"),
                ],
                help_text="To whom the contract is available",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="charactercontractitem",
            name="raw_quantity",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
