# Generated by Django 3.1.1 on 2020-09-26 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0002_load_eveunit'),
        ('memberaudit', '0004_corporationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSkills',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='memberaudit.owner')),
                ('total_sp', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unallocated_sp', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_skill_level', models.PositiveIntegerField()),
                ('skillpoints_in_skill', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('trained_skill_level', models.PositiveIntegerField()),
                ('owner_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberaudit.ownerskills')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('owner_skills', 'skill'), name='functional_pk_skills'),
        ),
    ]
