# Generated by Django 3.1.1 on 2020-10-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0005_auto_20201002_1228"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "basic_access",
                        "Can access this app and register and view his characters",
                    ),
                    ("view_guests", "Can view characters from users in guest state"),
                    (
                        "view_same_corporation",
                        "Can view characters and data of his main's corporation",
                    ),
                    (
                        "view_same_alliance",
                        "Can view characters and data of his main's alliance",
                    ),
                    ("view_everything", "Can view all characters and data"),
                ),
            },
        ),
    ]
