# Generated by Django 3.1.1 on 2020-10-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0005_characterjumpclone_characterjumpcloneimplant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterjumpcloneimplant",
            name="jump_clone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implants",
                to="memberaudit.characterjumpclone",
            ),
        ),
    ]
