# Generated by Django 3.1.1 on 2020-09-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0005_auto_20200926_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerskills',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='skills', serialize=False, to='memberaudit.owner'),
        ),
    ]
