# Generated by Django 3.1.1 on 2020-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0005_auto_20201001_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersyncstatus',
            name='sync_ok',
            field=models.BooleanField(db_index=True),
        ),
    ]
