# Generated by Django 3.1.8 on 2021-07-24 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0005_add_character_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "basic_access",
                        "Can access this app, register, and view own characters",
                    ),
                    ("share_characters", "Can share his/her characters"),
                    ("finder_access", "Can access character finder feature"),
                    ("reports_access", "Can access reports feature"),
                    ("characters_access", "Can view characters owned by others"),
                    ("view_roles", "Can view characters roles"),
                    ("view_shared_characters", "Can view shared characters"),
                    ("view_same_corporation", "Can view corporation characters"),
                    ("view_same_alliance", "Can view alliance characters"),
                    ("view_everything", "Can view all characters"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("assets", "assets"),
                    ("character_details", "character details"),
                    ("contacts", "contacts"),
                    ("contracts", "contracts"),
                    ("corporation_history", "corporation history"),
                    ("implants", "implants"),
                    ("jump_clones", "jump clones"),
                    ("location", "location"),
                    ("loyalty", "loyalty"),
                    ("mails", "mails"),
                    ("online_status", "online status"),
                    ("roles", "roles"),
                    ("skills", "skills"),
                    ("skill_queue", "skill queue"),
                    ("skill_sets", "skill sets"),
                    ("wallet_balance", "wallet balance"),
                    ("wallet_journal", "wallet journal"),
                    ("wallet_transactions", "wallet transactions"),
                    ("attributes", "attributes"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CharacterRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("hq", "Headquarters"),
                            ("other", "Other"),
                            ("", "Universal"),
                        ],
                        default="",
                        help_text="Location, if the role is specific to one. If blank, the role is generally applicable.",
                        max_length=5,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Director", "Director"),
                            ("Personnel_Manager", "Personnel Manager"),
                            ("Accountant", "Accountant"),
                            ("Security_Officer", "Security Officer"),
                            ("Factory_Manager", "Factory Manager"),
                            ("Station_Manager", "Station Manager"),
                            ("Auditor", "Auditor"),
                            ("Hangar_Take_1", "Hangar Take 1"),
                            ("Hangar_Take_2", "Hangar Take 2"),
                            ("Hangar_Take_3", "Hangar Take 3"),
                            ("Hangar_Take_4", "Hangar Take 4"),
                            ("Hangar_Take_5", "Hangar Take 5"),
                            ("Hangar_Take_6", "Hangar Take 6"),
                            ("Hangar_Take_7", "Hangar Take 7"),
                            ("Hangar_Query_1", "Hangar Query 1"),
                            ("Hangar_Query_2", "Hangar Query 2"),
                            ("Hangar_Query_3", "Hangar Query 3"),
                            ("Hangar_Query_4", "Hangar Query 4"),
                            ("Hangar_Query_5", "Hangar Query 5"),
                            ("Hangar_Query_6", "Hangar Query 6"),
                            ("Hangar_Query_7", "Hangar Query 7"),
                            ("Account_Take_1", "Account Take 1"),
                            ("Account_Take_2", "Account Take 2"),
                            ("Account_Take_3", "Account Take 3"),
                            ("Account_Take_4", "Account Take 4"),
                            ("Account_Take_5", "Account Take 5"),
                            ("Account_Take_6", "Account Take 6"),
                            ("Account_Take_7", "Account Take 7"),
                            ("Diplomat", "Diplomat"),
                            ("Config_Equipment", "Config Equipment"),
                            ("Container_Take_1", "Container Take 1"),
                            ("Container_Take_2", "Container Take 2"),
                            ("Container_Take_3", "Container Take 3"),
                            ("Container_Take_4", "Container Take 4"),
                            ("Container_Take_5", "Container Take 5"),
                            ("Container_Take_6", "Container Take 6"),
                            ("Container_Take_7", "Container Take 7"),
                            ("Rent_Office", "Rent Office"),
                            ("Rent_Factory_Facility", "Rent Factory Facility"),
                            ("Rent_Research_Facility", "Rent Research Facility"),
                            ("Junior_Accountant", "Junior Accountant"),
                            ("Config_Starbase_Equipment", "Config Starbase Equipment"),
                            ("Trader", "Trader"),
                            ("Communications_Officer", "Communications Officer"),
                            ("Contract_Manager", "Contract Manager"),
                            ("Starbase_Defense_Operator", "Starbase Defense Operator"),
                            ("Starbase_Fuel_Technician", "Starbase Fuel Technician"),
                            ("Fitting_Manager", "Fitting Manager"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        related_query_name="role",
                        to="memberaudit.character",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="characterrole",
            constraint=models.UniqueConstraint(
                fields=("character", "location", "role"),
                name="functional_pk_characterrole",
            ),
        ),
    ]
