# Generated by Django 3.1.1 on 2020-10-11 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0002_load_eveunit"),
        ("memberaudit", "0006_auto_20201010_1934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("CD", "character details"),
                    ("CA", "contacts"),
                    ("CR", "contracts"),
                    ("CH", "corporation history"),
                    ("JC", "jump clones"),
                    ("MA", "mails"),
                    ("SK", "skills"),
                    ("SQ", "skill queue"),
                    ("WB", "wallet balance"),
                    ("WJ", "wallet journal"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="CharacterContactLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_id",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_labels",
                        to="memberaudit.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=None, null=True)),
                ("is_watched", models.BooleanField(default=None, null=True)),
                ("standing", models.FloatField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="memberaudit.character",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        related_name="contacts", to="memberaudit.CharacterContactLabel"
                    ),
                ),
            ],
        ),
    ]
