# Generated by Django 3.1.1 on 2020-10-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0006_auto_20201002_1337"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "basic_access",
                        "Can access this app and register and view his characters",
                    ),
                    (
                        "manager_access",
                        "Can access manager features like character finder and reports",
                    ),
                    (
                        "view_same_corporation",
                        "Can view characters and data of his main's corporation",
                    ),
                    (
                        "view_same_alliance",
                        "Can view characters and data of his main's alliance",
                    ),
                    ("view_everything", "Can view all characters and data"),
                ),
            },
        ),
    ]
