# Generated by Django 3.1.1 on 2020-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0007_auto_20201004_2058"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="characterjumpclone",
            constraint=models.UniqueConstraint(
                fields=("character", "jump_clone_id"),
                name="functional_pk_characterjumpclone",
            ),
        ),
    ]
