# Generated by Django 3.1.1 on 2020-10-02 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_remove_fleetup_permission"),
        ("memberaudit", "0007_auto_20201002_1431"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSkillpoints",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="skillpoints",
                        serialize=False,
                        to="memberaudit.character",
                    ),
                ),
                (
                    "total",
                    models.BigIntegerField(
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unallocated", models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterUnreadMailCount",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="unread_mail_count",
                        serialize=False,
                        to="memberaudit.character",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterWalletBalance",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wallet_ballance",
                        serialize=False,
                        to="memberaudit.character",
                    ),
                ),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, max_digits=17),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="character",
            name="total_sp",
        ),
        migrations.RemoveField(
            model_name="character",
            name="total_unread_count",
        ),
        migrations.RemoveField(
            model_name="character",
            name="unallocated_sp",
        ),
        migrations.RemoveField(
            model_name="character",
            name="wallet_balance",
        ),
        migrations.AlterField(
            model_name="character",
            name="character_ownership",
            field=models.OneToOneField(
                help_text="ownership of this character on Auth",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberaudit_character",
                to="authentication.characterownership",
            ),
        ),
    ]
