# Generated by Django 3.1.1 on 2020-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0007_character_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
