# Generated by Django 3.1.1 on 2020-09-26 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0002_load_eveunit'),
        ('memberaudit', '0007_auto_20200926_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='memberaudit.owner')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='WalletJournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=17, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=17, null=True)),
                ('context_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('context_id_type', models.CharField(choices=[('NON', 'undefined'), ('STA', 'station_id'), ('MTR', 'market_transaction_id'), ('CHR', 'character_id'), ('COR', 'corporation_id'), ('ALL', 'alliance_id'), ('EVE', 'eve_system'), ('INJ', 'industry_job_id'), ('CNT', 'contract_id'), ('PLN', 'planet_id'), ('SYS', 'system_id'), ('TYP', 'type_id ')], max_length=3)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('ref_type', models.CharField(max_length=32)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=17, null=True)),
                ('first_party', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wallet_journal_entry_first_party_set', to='eveuniverse.eveentity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberaudit.owner')),
                ('second_party', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wallet_journal_entry_second_party_set', to='eveuniverse.eveentity')),
                ('tax_receiver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wallet_journal_entry_tax_receiver_set', to='eveuniverse.eveentity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='walletjournalentry',
            constraint=models.UniqueConstraint(fields=('owner', 'entry_id'), name='functional_pk_walletjournalentry'),
        ),
    ]
