# Generated by Django 2.2.10 on 2020-09-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0008_auto_20200926_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberaudit',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('unrestricted_access', 'Can view all characters and data'))},
        ),
    ]
