# Generated by Django 3.1.1 on 2020-10-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0008_auto_20201002_1654"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CharacterUnreadMailCount",
            new_name="CharacterMailUnreadCount",
        ),
    ]
