# Generated by Django 3.1.1 on 2020-10-02 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0009_auto_20201002_1704"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermailunreadcount",
            name="total",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characterskillpoints",
            name="total",
            field=models.BigIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
