# Generated by Django 3.1.1 on 2020-10-15 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0009_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactercontractitem",
            name="is_included",
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name="characterjumpclone",
            name="jump_clone_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="charactermail",
            name="mail_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="charactermailinglist",
            name="list_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="charactermaillabel",
            name="name",
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="active_skill_level",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="trained_skill_level",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="characterskillqueueentry",
            name="finished_level",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="characterskillqueueentry",
            name="queue_position",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="characterwalletjournalentry",
            name="context_id_type",
            field=models.CharField(
                choices=[
                    ("NON", "undefined"),
                    ("STA", "station ID"),
                    ("MTR", "market transaction ID"),
                    ("CHR", "character ID"),
                    ("COR", "corporation ID"),
                    ("ALL", "alliance ID"),
                    ("EVE", "eve system"),
                    ("INJ", "industry job ID"),
                    ("CNT", "contract ID"),
                    ("PLN", "planet ID"),
                    ("SYS", "system ID"),
                    ("TYP", "type ID"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="doctrineshipskill",
            name="level",
            field=models.PositiveIntegerField(
                help_text="Minimum required skill level",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
