# Generated by Django 3.1.1 on 2020-10-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0010_db_optimizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermail",
            name="is_read",
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
