# Generated by Django 3.1.1 on 2020-10-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0010_auto_20201002_1705"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterwalletbalance",
            old_name="wallet_balance",
            new_name="total",
        ),
    ]
