# Generated by Django 3.1.1 on 2020-10-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0011_auto_20201002_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterwalletbalance",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="wallet_balance",
                serialize=False,
                to="memberaudit.character",
            ),
        ),
    ]
