# Generated by Django 3.1.1 on 2020-10-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0002_load_eveunit"),
        ("memberaudit", "0011_unread_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctrineship",
            name="is_visible",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Non visible doctrine ships are not shown to users on their character sheet and used for reporting only.",
            ),
        ),
        migrations.AddField(
            model_name="doctrineship",
            name="ship_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AlterField(
            model_name="doctrine",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this doctrine is in active use",
            ),
        ),
        migrations.AlterField(
            model_name="doctrine",
            name="ships",
            field=models.ManyToManyField(
                related_name="doctrines", to="memberaudit.DoctrineShip"
            ),
        ),
    ]
