# Generated by Django 3.1.1 on 2020-10-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0015_auto_20201021_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterOnlineStatus",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="online_status",
                        serialize=False,
                        to="memberaudit.character",
                    ),
                ),
                ("last_login", models.DateTimeField(default=None, null=True)),
                ("last_logout", models.DateTimeField(default=None, null=True)),
                ("logins", models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="characterlocation",
            name="id",
        ),
        migrations.AlterField(
            model_name="characterlocation",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="location",
                serialize=False,
                to="memberaudit.character",
            ),
        ),
    ]
