# Generated by Django 3.1.1 on 2020-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0016_auto_20201021_1735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("AS", "assets"),
                    ("CD", "character details"),
                    ("CA", "contacts"),
                    ("CR", "contracts"),
                    ("CH", "corporation history"),
                    ("LO", "location"),
                    ("JC", "jump clones"),
                    ("MA", "mails"),
                    ("OS", "online status"),
                    ("SK", "skills"),
                    ("SQ", "skill queue"),
                    ("WB", "wallet balance"),
                    ("WJ", "wallet journal"),
                ],
                max_length=2,
            ),
        ),
    ]
