# Generated by Django 3.1.1 on 2020-10-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0019_auto_20201022_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("assets", "assets"),
                    ("character_details", "character details"),
                    ("contacts", "contacts"),
                    ("contracts", "contracts"),
                    ("corporation_history", "corporation history"),
                    ("location", "location"),
                    ("loyalty", "loyalty"),
                    ("jump_clones", "jump clones"),
                    ("mails", "mails"),
                    ("online_status", "online status"),
                    ("skills", "skills"),
                    ("skill_queue", "skill queue"),
                    ("wallet_balance", "wallet balance"),
                    ("wallet_journal", "wallet journal"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
