# Generated by Django 3.1.1 on 2020-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0022_auto_20201022_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterasset",
            name="is_blueprint_copy",
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
