# Generated by Django 3.1.2 on 2020-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0025_auto_20201026_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactermail",
            name="labels",
            field=models.ManyToManyField(
                related_name="mails", to="memberaudit.CharacterMailLabel"
            ),
        ),
        migrations.DeleteModel(
            name="CharacterMailMailLabel",
        ),
    ]
